# Generated by Django 3.1.7 on 2021-05-09 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mths',
            new_name='Phone_no',
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='months_due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
