# Generated by Django 3.1.7 on 2021-05-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0002_auto_20210509_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
