# Generated by Django 3.1.7 on 2021-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0003_auto_20210509_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media')),
                ('img2', models.ImageField(upload_to='media')),
                ('img3', models.ImageField(upload_to='media')),
                ('img4', models.ImageField(upload_to='media')),
                ('img5', models.ImageField(upload_to='media')),
            ],
        ),
    ]
