# Generated by Django 3.1.7 on 2021-05-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0004_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='media',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='media',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='media',
            name='img5',
        ),
    ]
