# Generated by Django 3.1.7 on 2021-05-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0005_auto_20210511_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='img1',
            new_name='img',
        ),
    ]
