# Generated by Django 3.1.7 on 2021-05-12 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0006_auto_20210511_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_paid',
            field=models.DateField(default=datetime.datetime(2021, 5, 12, 19, 30, 38, 167884, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
